import { Geist, Geist_Mono, Chakra_Petch, Black_Ops_One } from "next/font/google";
import "./globals.css";

const chakraPetch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["400", "700"], // Choose available weights
  variable: "--font-chakra-petch", // Define a CSS variable
});

const blackOpsOne = Black_Ops_One({
  subsets: ["latin"],
  weight: ["400"], // Only available weight for Black Ops One
  variable: "--font-black-ops-one",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Premal's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${blackOpsOne.variable} ${chakraPetch.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
